version: "3.8"

services:
  catalogdb:
    image: mongo

  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketdb:
    image: redis:alpine

  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discountdb:
    image: postgres

  discount.api:
    image: discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  ordering.api:
    image: orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  ocelotapigw:
    image: ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

volumes:
  mongo_data:
  postgres_data:
  mssql_data:
  portainer_data:
  pgadmin_data:
